org: php1301
app: my-aws-node-express-api-app
service: my-aws-node-express-api-app

frameworkVersion: '2'

package:
excludeDevDependencies: false


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'


plugins:
  - serverless-plugin-include-dependencies
  
functions:
  api:
    timeout: 15
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
